openapi: 3.0.0
servers:
  - description: 臺北市教育局單一身份驗證服務伺服器
    url: https://ldap.tp.edu.tw/api/v2/
info:
  version: '2.0'
  title: 臺北市教育局單一身份驗證服務
  description: |-
    這是「臺北市教育局單一身份驗證服務」開發專案所提供的REST服務，用來提供各級學程教育開放資料，資料內容依照個資法規定劃分為：公開資料及個人資料。前者可使用專案授權取得，後者需透過使用者行使同意權方能取得，由於個人資料中包含有未滿13歲之學童個資，因此申請介接專案之廠商或學校，若服務對象包含13歲以下之學童，依法應取得家長之書面同意始能申請介接。
    本服務依照各種不同應用場合，提供四種不同的授權方法進行資料介接：專案授權、個資授權、代理授權、特權專案。不同授權模式之使用時機說明如下：
    專案授權：存取無需使用者介入之學校公開資料，此範圍之資料為移除個資之軌跡資料，當須揭露相關當事人時，以其 UUID 代替。UUID 可由個資授權及代理授權查詢出真實資料。
    個資授權：存取教育人員個資，應經過個資當事人行使同意權才能取得。個資當事人隨時可以透過服務網站終止授權，當授權終止時介接專案將無法再取得當事人個資。
    代理授權：由依法保存和運用個資之機關學校，因執行法定業務之需求，將其一部份業務委託廠商進行系統開發時，可以無需個資當事人同意利用其個資，詳細規定請參閱個資法。為滿足此需求，系統提供代理授權功能。使用方法為：學校系統管理人員透過服務網站建立個人存取金鑰，將個人存取金鑰交付廠商，廠商可透過此金鑰存取學校系統管理人員所設定之特定資料範圍。若學校要終止此項授權，只要透過服務網站移除該金鑰即可。代理授權對個資當事人權益的影響巨大，請務必進行法律諮詢後再實施。
    特權專案：經教育局認定可以管理全域資料的專案。無需學校管理員或資料當事人之授權，可以進行全部資料操作。
security:
  - proxy: []
  - user:
    - me
    - email
    - user
    - idno
    - profile
    - account
  - project:
    - school
    - admin
paths:
  /school:
    get:
      summary: 取得學校清單
      security:
        - project:
          - school
      description: 取得臺北市高中(含)以下各級學校清單
  /school/{dc}:
    get:
      summary: 取得指定學校資料
      security:
        - project:
          - school
    patch:
      summary: 修改學校資訊
      security:
        - project:
          - proxy
  /school/{dc}/people:
    get:
      summary: 搜尋符合條件的人員
      security:
        - project:
          - school
      description: 通常 idno 和 sysid 會單獨使用，其他條件可以複合搜尋
    post:
      summary: 新增人員
      security:
        - project:
          - proxy
  /school/{dc}/people/{uuid}:
    get:
      summary: 取得指定人員詳細資訊
      security:
        - project:
          - proxy
    patch:
      summary: 修改指定人員詳細資訊
      security:
        - project:
          - proxy
    delete:
      summary: 修改指定人員詳細資訊
      security:
        - project:
          - proxy
  /school/{dc}/teachers:
    get:
      summary: 取得學校教師清單
      security:
        - project:
          - school
  /school/{dc}/ou:
    get:
      summary: 取得行政單位清單
      security:
        - project:
          - school
  /school/{dc}/ou/{ou}:
    get:
      summary: 取得指定的行政單位資料
      security:
        - project:
          - school
  /school/{dc}/ou/{ou}/teachers:
    get:
      summary: 取得行政單位在職人員清單
      security:
        - project:
          - school
  /school/{dc}/ou/{ou}/role:
    get:
      summary: 取得行政單位職務清單
      security:
        - project:
          - school
  /school/{dc}/ou/{ou}/role/{role}:
    get:
      summary: 取得指定的職務資料
      security:
        - project:
          - school
  /school/{dc}/ou/{ou}/role/{role}/teachers:
    get:
      summary: 取得職務在職人員清單
      security:
        - project:
          - school
  /school/{dc}/subject:
    get:
      summary: 取得課程（科目）清單
      security:
        - project:
          - school
  /school/{dc}/subject/{subject}:
    get:
      summary: 取得課程（科目）資料
      security:
        - project:
          - school
  /school/{dc}/subject/{subject}/teachers:
    get:
      summary: 取得課程（科目）任課教師清單
      security:
        - project:
          - school
  /school/{dc}/subject/{subject}/classes:
    get:
      summary: 取得課程（科目）授課班級清單
      security:
        - project:
          - school
  /school/{dc}/class:
    get:
      summary: 取得學校班級清單
      security:
        - project:
          - school
  /school/{dc}/class/{class}:
    get:
      summary: 取得學校班級資料
      security:
        - project:
          - school
  /school/{dc}/class/{class}/students:
    get:
      summary: 取得班級學生清單
      security:
        - project:
          - school
  /school/{dc}/class/{class}/parents:
    get:
      summary: 取得班級家長清單
      security:
        - project:
          - school
  /school/{dc}/class/{class}/teachers:
    get:
      summary: 取得班級教師清單
      security:
        - project:
          - school
  /school/{dc}/class/{class}/subjects:
    get:
      summary: 取得班級課程（授課科目）清單
      security:
        - project:
          - school
  /email:
    get:
      summary: 取得登入者的電子郵件
      security:
        - project:
          - user
  /me:
    get:
      summary: 取得登入者的姓名和電子郵件
      security:
        - project:
          - user
  /idno:
    get:
      summary: 取得登入者的身分證字號
      security:
        - project:
          - user
  /user:
    get:
      summary: 取得登入者的一般資訊
      security:
        - project:
          - user
    patch:
      summary: 修改登入者的一般資訊
      security:
        - project:
          - user
  /profile:
    get:
      summary: 取得登入者的身份識別資訊
      security:
        - project:
          - user
  /account:
    patch:
      summary: 修改登入者的帳號密碼
      security:
        - project:
          - user
  /logout:
    get:
      security:
        - project:
          - user
  /validate/{token}:
    get:
      security:
        - project:
          - school
  /clients:
    get:
      security:
        - project:
          - school
  /scopes:
    get:
      security:
        - project:
          - school
components:
  securitySchemes:
    proxy:
      type: http
      scheme: bearer
    user:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://ldap.tp.edu.tw/oauth/authorize'
          tokenUrl: 'https://ldap.tp.edu.tw/oauth/token'
          scopes:
            me: 想要取得您的電子郵件和姓名
            email: 想要取得您的電子郵件
            user: 想要取得您的識別代號、姓名、電子郵件、手機號碼等資訊
            idno: 想要取得您的身分證字號
            profile: 想要取得您的身分、所屬機構、單位職稱、任教班級、任教科目、就讀年班等資訊
            account: 想要修改您的自訂帳號、電子郵件、手機號碼和密碼
    project:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://ldap.tp.edu.tw/oauth/token'
          scopes:
            school: 想要讀取學校公開資訊
            admin: 想要更新所有學校資訊，以及增刪修所有學校人員