<?php

return [
    'ps' => [
        'debug' => true,
        'oauth_id' => env('PS_CLIENT_ID'),
        'oauth_secret' => urlencode(env('PS_CLIENT_SECRET')),
        'aes_key' => env('PS_AES_KEY'),
        'aes_iv' => env('PS_AES_IV'),
        'base_uri' => env('PS_APISERVER'),
        'school_info' => 'public/{sid}/schoolinfo/schoolinfo',
        'department_info' => 'public/{sid}/schoolinfo/departmentinfo',
        'classes_info' => 'public/{sid}/schoolinfo/clsinfo',
        'special_info' => 'public/{sid}/schoolinfo/specilinfo',
        'calendar_info' => 'public/{sid}/schoolinfo/calendarinfo',
        'teachers_info' => 'user/{sid}/teachers/teacher/all',
        'student_info' => 'user/{sid}/students/student/{stdno}',
        'student_detail' => 'user/{sid}/profile/profile/{stdno}',
        'students_in_class' => 'user/{sid}/students/class/{clsid}',
        'leaders_in_class' => 'user/{sid}/students/leaders/{seme}/{clsid}',
        'student_subjects_score' => 'user/{sid}/students/subjectscore/{seme}/{stdno}',
        'student_domains_score' => 'user/{sid}/students/stdlibscore/{seme}/{stdno}',
        'student_attendance_record' => 'user/{sid}/students/absdat/{seme}/{stdno}',
        'student_health_record' => 'user/{sid}/students/health/{seme}/{stdno}',
        'student_parents_info' => 'user/{sid}/parents/student/{stdno}',
        'teacher_info' => 'user/{sid}/teachers/teacher/{teaid}',
        'teacher_detail' => 'user/{sid}/profile/profile/{teaid}',
        'teachers_in_class' => 'user/{sid}/teachers/class/{clsid}',
        'teacher_schedule' => 'admin/{sid}/subjects/teacher/{teaid}',
        'teacher_tutor_students' => 'user/{sid}/teachers/student/{teaid}',
        'subject_info' => 'admin/{sid}/subjects/subject/{subjid}',
        'subject_for_class' => 'admin/{sid}/subjects/class/{clsid}',
        'subject_assign_to_teacher' => 'admin/{sid}/subjects/teacher/{teaid}',
        'classses_by_grade' => 'admin/{sid}/classes/grade/{grade}',
        'classs_schedule' => 'admin/{sid}/classes/class/{clsid}',
        'classs_info' => 'admin/{sid}/classes/classinfo/{clsid}',
        'library_books' => 'admin/{sid}/libraryinfo/bookinfo',
        'class_lend_record' => 'admin/{sid}/libraryinfo/yearlendtot/{seme}/{clsid}',
        'book_info' => 'admin/{sid}/libraryinfo/bookisbn/{isbn}',
    ],
    'js' => [
        'debug' => true,
        'oauth_id' => env('JS_CLIENT_ID'),
        'oauth_secret' => env('JS_CLIENT_SECRET'),
        'base_uri' => 'https://ap2.mwdb.tp.edu.tw/',
        'schools_info' => 'school/all',
        'school_info' => 'school/{sid}',
        'teachers_info' => 'school/{sid}/teachers',
        'units_info' => 'school/{sid}/unit',
        'subjects_info' => 'school/{sid}/subject',
        'classes_info' => 'school/{sid}/class',
        'roles_info' => 'school/{sid}/unit/{ou}',
        'students_in_class' => 'school/{sid}/class/{clsid}/students',
        'person_info' => 'school/{sid}/people/{idno}',
        'person_change' => 'school/{sid}/people/changed/{year-month}',
    ],
];
