<?php

return [
    'ps' => [
        'debug' => true,
        'oauth_id' => env('PS_CLIENT_ID'),
        'oauth_secret' => urlencode(env('PS_CLIENT_SECRET')),
        'aes_key' => env('PS_AES_KEY'),
        'aes_iv' => env('PS_AES_IV'),
        'base_uri' => 'https://163.21.249.80/dataapi_web/',
        'school_info' => 'public/{sid}/schoolinfo/schoolinfo',
        'department_info' => 'public/{sid}/schoolinfo/departmentinfo',
        'classes_info' => 'public/{sid}/schoolinfo/clsinfo',
        'special_info' => 'public/{sid}/schoolinfo/specilinfo',
        'calendar_info' => 'public/{sid}/schoolinfo/calendarinfo',
        'student_info' => 'user/{sid}/students/student/{stdno}',
        'students_in_class' => 'user/{sid}/students/class/{clsid}',
        'leaders_in_class' => 'user/{sid}/students/leaders/{seme}/{clsid}',
        'student_subjects_score' => 'user/{sid}/students/subjectscore/{seme}/{stdno}',
        'student_domains_score' => 'user/{sid}/students/stdlibscore/{seme}/{stdno}',
        'student_attendance_record' => 'user/{sid}/students/absdat/{seme}/{stdno}',
        'student_health_record' => 'user/{sid}/students/health/{seme}/{stdno}',
        'student_parents_info' => 'user/{sid}/parents/student/{stdno}',
        'teacher_info' => 'user/{sid}/teachers/teacher/{teaid}',
        'teachers_in_class' => 'user/{sid}/teachers/class/{clsid}',
        'teacher_schedule' => 'user/{sid}/subjects/teacher/{teaid}',
        'teacher_tutor_students' => 'user/{sid}/teachers/student/{teaid}',
        'subject_info' => 'admin/{sid}/subjects/subject/{subjid}',
        'subject_for_class' => 'admin/{sid}/subjects/class/{clsid}',
        'subject_assign_to_teacher' => 'admin/{sid}/subjects/teacher/{teaid}',
        'classses_by_grade' => 'admin/{sid}/classes/grade/{grade}',
        'classs_schedule' => 'admin/{sid}/classes/class/{clsid}',
        'classs_info' => 'admin/{sid}/classes/classinfo/{clsid}',
        'library_books' => 'admin/{sid}/libraryinfo/bookinfo',
        'class_lend_record' => 'admin/{sid}/libraryinfo/yearlendtot/{seme}/{clsid}',
        'book_info' => 'admin/{sid}/libraryinfo/bookisbn/{isbn}',
    ],
    'js' => [
        'oauth_id' => env('JS_CLIENT_ID'),
        'oauth_secret' => env('JS_CLIENT_SECRET'),
        'oauth_ip' => env('JS_SERVICE_IP'),
    ],
];
